### ISSUE TITLE
Make existing code PEP8 compliant

### ISSUE THREAD

**Issue by bernhold** [HPC-SimTools/IPS-framework#25]
Enforce coding standards

**Comment by elwasif** [comment]
I'm still getting several Pep8 warnings in services.py, many on Exceptions

**Comment by rosswhitfield** [comment]
I'm guessing that's the bare except warnings, I had disabled those in the flake8 config (E722 in https://github.com/HPC-SimTools/IPS-framework/blob/master/setup.cfg#L1-L11) with intent to go back and fix them and forgot about that. The easy solution is just to use the base exception but really that isn't any better than bare except but I may end up doing that. I also increased the max-line-length (doubled to 160) simply because there were some many lines that would be required to change and the default is I think too small.

I will go fix the bare excepts, and I was also meaning to add in the test folder as well. I don't know what you think about a suitable max-line-lenght.

What tool are you using to check the PEP8 compliance? I can make sure it has the same config as flake8.

**Comment by elwasif** [comment]
I'm using PyCharm's built in checker. I haven't tried to change its default configuration, but I guess there's a way to do that. I agee that bare exceptions vs base exceptions isn't a big jump, but I hope we can limit the places we're doing that as we go through the code.
